### ISSUE TITLE
[Enchancement] Enhance shadow handling

### ISSUE THREAD

**Issue by kvtemadden** [suryanshsingh2001/mockly#18]
### **Is your enhancement request related to a problem? Please describe.**
The current implementation of shadows doesn't handle very well. It draws a border but doesn't fill to provide a nice shadow, so blur doesn't impact much when you adjust the value.

### **Describe the enhancement you'd like**
I would like the feature to improve shadow handling, to both improve the visual appearance of shadows and to increase the amount of control a user has on a shadow.

### **Describe alternatives you've considered & Possible Implementation Details**
I've already built a solution for this, which provides a small `popover` menu when a settings button is clicked, providing the user with more options around shadows. Other options include `X offset`, `Y offset`, `color` and `blur` is also included (but displays any existing state provided by the slider).

This improvement also improves the visuals of shadows on the UI, making it a much nicer UX than the existing implementation which only provides a border/frame shadow. This new suggestion also maps transparent images to provide an accurate image shadow. If border radius is added to a `png` with a transparent background then it provides a filled background based on `shadow.color` and rounds the edges of the fill. Further context provided below.

### **Additional context**
I'd like to open a PR with the following implementation if you're happy for me to:

**Existing**
![Screen Recording 2024-09-30 at 12 44 10](https://github.com/user-attachments/assets/513c8dd1-5f40-4e08-b1fa-7a976bdeecff)

**Suggested implementation**
![Screen Recording 2024-09-30 at 12 43 08](https://github.com/user-attachments/assets/653e4e5c-86d3-4e65-bf44-734b7b57b262)

---

### **Optional Sections (if relevant):**

- **Priority (Low / Medium / High)**  Low
- **Are you willing to submit a PR for this enhancement?**  Yes
- **Does this enhancement require changes in documentation?** No

**Comment by kvtemadden** [comment]
Hey @suryanshsingh2001 👋 - I noticed this shadow issue whilst working on the flickering editor, wondered if you would be okay with me opening a PR against this that's ready for review?

**Comment by suryanshsingh2001** [comment]
@kvtemadden, Absolutely, assigned you the issue.
