### ISSUE TITLE
[Enchancement] Add more setting for text styling

### ISSUE THREAD

**Issue by Laikokwui** [suryanshsingh2001/mockly#21]
### **Is your enhancement request related to a problem? Please describe.**
The user couldn't style the text further like adding underline to the text, change to use different font family, add borders to the text.

### **Describe the enhancement you'd like**
It would be great to have a section to further change the style of the text.

### **Possible Implementation Details**
Add variables to let text show different font family, border style, text decoration. 
If user are allow to add more than 1 text i will look into how to store different style for different text.

### **Optional Sections (if relevant):**

- **Priority (Low / Medium / High)**  High
- **Are you willing to submit a PR for this enhancement?**  Yes
- **Does this enhancement require changes in documentation?** Yes

**Comment by suryanshsingh2001** [comment]
Hi @Laikokwui 

Thank you for your enhancement request!

Here is a task list to get you started in this:

- [ ] Identify and confirm additional text styles to be included (e.g., font family, underline, borders).
- [ ] Follow the same design guidelines for shadows as used elsewhere in the project.
- [ ] Implement a **Popover** component for handling all text style features (font family, text decoration, etc.).
- [ ] Add variables to support different font families, border styles, and text decorations.
- [ ] Test to ensure that all added styles are applied correctly and consistently in the text component.

For your reference, here is how shadow setting are displayed.

![image](https://github.com/user-attachments/assets/d78fc92a-87f1-4cfb-a34a-b51d8102967d)

**Comment by kirito05** [comment]
Can I work on this enhancement ??

**Comment by suryanshsingh2001** [comment]
> Can I work on this enhancement ??

@kirito05 Hey, I have assigned you the issue. Feel free to work with @Laikokwui on this issue. He is having some issues with text positioning. Or you can work independently as well.

**Comment by suryanshsingh2001** [comment]
> Hi @Laikokwui
> 
> Thank you for your enhancement request!
> 
> Here is a task list to get you started in this:
> 
> * [ ]  Identify and confirm additional text styles to be included (e.g., font family, underline, borders).
> * [ ]  Follow the same design guidelines for shadows as used elsewhere in the project.
> * [ ]  Implement a **Popover** component for handling all text style features (font family, text decoration, etc.).
> * [ ]  Add variables to support different font families, border styles, and text decorations.
> * [ ]  Test to ensure that all added styles are applied correctly and consistently in the text component.
> 
> For your reference, here is how shadow setting are displayed.
> 
> ![image](https://private-user-images.githubusercontent.com/80690023/372604205-d78fc92a-87f1-4cfb-a34a-b51d8102967d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzQ1MjEsIm5iZiI6MTcyNzkzNDIyMSwicGF0aCI6Ii84MDY5MDAyMy8zNzI2MDQyMDUtZDc4ZmM5MmEtODdmMS00Y2ZiLWEzNGEtYjUxZDgxMDI5NjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA1NDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTJlMzc0NzE1M2FiZjBlMjIxZTNjZDA0MjMwMzFjOTQ4YzdmYmVmZDUxOThmMjExMzA0OTlhNjYyYjNjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lqUlZ4Mgn2NO7h5e4_Q8vNL6q9OcSL6QdgkcmYszcvM)

Here is some implementation requirements.

**Comment by suryanshsingh2001** [comment]
> > Hi @Laikokwui
> > Thank you for your enhancement request!
> > Here is a task list to get you started in this:
> > 
> > * [ ]   Identify and confirm additional text styles to be included (e.g., font family, underline, borders).
> > * [ ]   Follow the same design guidelines for shadows as used elsewhere in the project.
> > * [ ]   Implement a **Popover** component for handling all text style features (font family, text decoration, etc.).
> > * [ ]   Add variables to support different font families, border styles, and text decorations.
> > * [ ]   Test to ensure that all added styles are applied correctly and consistently in the text component.
> > 
> > For your reference, here is how shadow setting are displayed.
> > ![image](https://private-user-images.githubusercontent.com/80690023/372604205-d78fc92a-87f1-4cfb-a34a-b51d8102967d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzQ1MjEsIm5iZiI6MTcyNzkzNDIyMSwicGF0aCI6Ii84MDY5MDAyMy8zNzI2MDQyMDUtZDc4ZmM5MmEtODdmMS00Y2ZiLWEzNGEtYjUxZDgxMDI5NjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA1NDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTJlMzc0NzE1M2FiZjBlMjIxZTNjZDA0MjMwMzFjOTQ4YzdmYmVmZDUxOThmMjExMzA0OTlhNjYyYjNjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lqUlZ4Mgn2NO7h5e4_Q8vNL6q9OcSL6QdgkcmYszcvM)
> 
> Here are some implementation requirements to get your started.
