### ISSUE TITLE
[Bug] Handle NaN Value: Update UI to Display '0px'

### ISSUE THREAD

**Issue by rahulchaudhary2244** [suryanshsingh2001/mockly#23]
### **Describe the bug**
Clearing the Blur property in the Shadow settings currently results in "NaN" text being displayed on the UI. This issue needs to be addressed, and "NaN" should be handled appropriately to improve the user experience.

### **To Reproduce**
1. Go to 'Shadow Settings'
2. Clear the text field of 'Blur' property.
3. Notice the text changes to 'Shadow: NaNpx' on UI

### **Expected behavior**
The UI should display '0px' instead of 'NaNpx' to ensure clarity and prevent confusion for users.

### **Screenshots**
<img width="694" alt="Screenshot 2024-10-02 at 1 01 25 AM" src="https://github.com/user-attachments/assets/61ad1a6f-b797-41b4-a356-86bc54ede973">
<img width="681" alt="Screenshot 2024-10-02 at 1 01 48 AM" src="https://github.com/user-attachments/assets/fc7fd513-728d-4bfe-ac66-794ce3bda776">

### **Optional Sections (if relevant):**

- **Priority (Low / Medium / High)** 
- **Is this issue blocking your progress?**  - No
- **Can you submit a PR to fix this?** - Yes

**Comment by rahulchaudhary2244** [comment]
Hi @suryanshsingh2001 , I have discovered a bug and would appreciate it if you could assign it to me for resolution.

**Comment by suryanshsingh2001** [comment]
@rahulchaudhary2244 Good catch, you can work on this.
