### ISSUE TITLE
[Enchancement] Cursor position when dragging

### ISSUE THREAD

**Issue by kvtemadden** [suryanshsingh2001/mockly#27]
### **Is your enhancement request related to a problem? Please describe.**
The current cursor position when dragging snaps to the top left of the image or text, which makes it quite difficult to position things close to the canvas boundary.

### **Describe the enhancement you'd like**
I would like the feature to maintain cursor position where it originally clicked on the image whilst dragging (similar to other tools like Canva)

### **Possible Implementation Details**
Track the offset from the image position when dragging and use that as the cursor point whilst dragging.

### **Additional context**

Current:
![Screen Recording 2024-10-02 at 15 27 13](https://github.com/user-attachments/assets/f52f572b-d9f9-4c78-b990-d280f5f522fe)

Suggested:
![Screen Recording 2024-10-02 at 15 26 32](https://github.com/user-attachments/assets/deb2781e-2963-4d2f-8e4c-b9a9cfc5989f)

---

### **Optional Sections (if relevant):**

- **Are you willing to submit a PR for this enhancement?**   Yes
- **Does this enhancement require changes in documentation?** No

**Comment by kvtemadden** [comment]
Hey @suryanshsingh2001, me again 😄, I have a working solution for this if I can open a PR?

**Comment by suryanshsingh2001** [comment]
@kvtemadden , Absolutely, please proceed 😊.
