### ISSUE TITLE
[Feature Request] More Download Options (JPG, PNG, and Other Formats)

### ISSUE THREAD

**Issue by suryanshsingh2001** [suryanshsingh2001/mockly#3]
### Problem Description
Currently, the tool only offers limited download options. Users may need to download their mockups in different formats (e.g., JPG, PNG) based on their specific use cases or preferences.

Example: "The current export options do not allow users to download in a variety of formats, limiting flexibility for different use cases such as web use, presentations, or printing."

### Desired Enhancement
I would like to introduce more download options, allowing users to export their designs in popular formats such as JPG and PNG. Other formats like SVG or PDF could also be considered to cater to different needs.

### Alternatives Considered
I considered using external tools to convert the exported image, but integrating this directly into the tool would make it more user-friendly and efficient for users.

### Possible Implementation
- [ ] Add export options for JPG and PNG formats
- [ ] Consider adding other formats like SVG or PDF for flexibility
- [ ] Ensure that the quality of the exports is maintained across all formats
- [ ] Add a dropdown or menu in the UI to allow users to select their preferred format before download

---

### Optional Sections:

- **Priority**: Medium
- **Are you willing to submit a PR for this enhancement?** Yes
- **Does this enhancement require changes in documentation?** No

**Comment by Alienimnida** [comment]
Hello I would like to take this up💫

**Comment by suryanshsingh2001** [comment]
@Alienimnida Hey, I have assigned you the issue, you can work independently or with the current person working on this issue.
https://github.com/suryanshsingh2001/mockly/pull/5

**Comment by Alienimnida** [comment]
Oh ok was someone already working on this?

**Comment by suryanshsingh2001** [comment]
> Oh ok was someone already working on this?

Yes, please refer to PR https://github.com/suryanshsingh2001/mockly/pull/5
Feel free to work on other issues or submit your own issue [here](https://github.com/suryanshsingh2001/mockly/issues/new/choose)

**Comment by suryanshsingh2001** [comment]
Closing this issue, feature implemented however, there refactoring needed.

**Comment by Alienimnida** [comment]
Oh no it's closed? Should I work on it then?

**Comment by suryanshsingh2001** [comment]
> Oh no it's closed? Should I work on it then?

Hey, there is some refactoring required for the download logic of the app. You can create an issue for this, or I'll create one later.
