### ISSUE TITLE
[Enchancement] Text wrapping for longer sentences 

### ISSUE THREAD

**Issue by kirito05** [suryanshsingh2001/mockly#34]
### **Is your enhancement request related to a problem? Please describe.**
The text on the canvas does not wrap after it hits the screen limit.

### **Describe the enhancement you'd like**
I would like a feature where the text wraps itself up after a sentence reaches the screen limit. 

### **Possible Implementation Details**
Track the text limit, compare it with the screen size, and change the position of the text on the canvas

### **Additional context**
Current: 

---

https://github.com/user-attachments/assets/0ca7a1f3-489a-4c76-a1bb-6e714d847d0e

Suggested:

https://github.com/user-attachments/assets/39e89122-da5f-44c2-afa1-1bace37847b9

### **Optional Sections (if relevant):**

- **Are you willing to submit a PR for this enhancement?**  Yes
- **Does this enhancement require changes in documentation?** No

**Comment by kirito05** [comment]
Hey @suryanshsingh2001, I have a working solution for this can I submit a PR for this, also I have a few more issues/changes I found that can be helpful but I was not sure whether they were required or only I felt that these changes are required. How can I Proceed with those changes ??

**Comment by suryanshsingh2001** [comment]
@kirito05 Thanks for bringing this up! Feel free to submit a PR, and we'll take a look.

As for additional issues, you're welcome to raise them anytime. We’ll review and assign ypu accordingly. If they’re related to this issue, please mention them, and we can assess if they're necessary.
