### ISSUE TITLE
[Enchancement] Set custom Images as the background.

### ISSUE THREAD

**Issue by kirito05** [suryanshsingh2001/mockly#38]
### **Is your enhancement request related to a problem? Please describe.**
The current background Image section doesn't have any feature to upload custom images or select any photo from the web other than the given custom images

### **Describe the enhancement you'd like**
In the Background Image section, it would be great to have a custom Image selection for the background image

<img width="346" alt="d1" src="https://github.com/user-attachments/assets/d76409e5-934c-4c5f-a4f7-b5064fcd3974">

### **Possible Implementation Details**
We can add new condition where the image is not only of the form "HTTP" but also "data:Image/"

<img width="431" alt="d2" src="https://github.com/user-attachments/assets/fb66309a-6362-4ca9-8352-ff7baab2dd37">

### **Additional context**
Here is a working solution for this:

https://github.com/user-attachments/assets/38191e85-6e09-4189-bb4c-b22cb71eda80

---

### **Optional Sections (if relevant):**

- **Are you willing to submit a PR for this enhancement?**  Yes
- **Does this enhancement require changes in documentation?** Yes
**Note** @suryanshsingh2001  : Update FAQs for this

**Comment by kirito05** [comment]
Hey @ suryanshsingh2001, it's @ kirito05 again, as I said in the previous issue, this is one of the features that would be great to add, as it gives more freedom to the user.

**Comment by suryanshsingh2001** [comment]
> Hey @ suryanshsingh2001, it's @ kirito05 again, as I said in the previous issue, this is one of the features that would be great to add, as it gives more freedom to the user.

Hey @kirito05, this feature looks good and aligns with what we needed. You can go ahead and create a PR for this.

One suggestion: could you refine the UI for the custom background button to make it look more polished?

**Comment by kirito05** [comment]
Ok will do that.

**Comment by kirito05** [comment]
https://github.com/user-attachments/assets/41c7208b-ebf0-47a3-b9c2-2be281b2b15d

Is the UI of the Custom button ok or is there anything else that needs to be done?

**Comment by suryanshsingh2001** [comment]
Hey @kirito05 ,
Try to follow the same design language with all the control buttons

- [ ] Remove dotted background for custom background modal
- [ ] Remove dotted background for  Upload From Computer
- [ ] Rename Upload From Computer button to browse files.
- [ ] For Browse files button  use ghost variant of (Button)[https://ui.shadcn.com/docs/components/button] component.
- [ ] Make sure paste Image Link here works

**Comment by suryanshsingh2001** [comment]
In review at preview branch
