### ISSUE TITLE
[Feature Request] Custom Screen Sizes Option

### ISSUE THREAD

**Issue by suryanshsingh2001** [suryanshsingh2001/mockly#4]
### Problem Description
The tool currently only supports preset screen sizes for mobile, tablet, and desktop. Users may need to define custom screen dimensions to better suit their specific design needs, such as creating screenshots for devices with uncommon resolutions or specific web layouts.

Example: "The current implementation only provides preset sizes, which limits the flexibility for users who require custom dimensions."

### Desired Enhancement
I would like to introduce an option that allows users to input custom screen sizes in addition to the default mobile, tablet, and desktop sizes. This would allow users to design and export mockups in any resolution they need.

### Alternatives Considered
I explored using external tools to crop or resize screenshots after export, but having this feature built directly into the tool would save users time and provide a more streamlined experience.

### Possible Implementation
- [ ] Add a custom size option where users can input their desired width and height in pixels
- [ ] Ensure the aspect ratio can be locked or unlocked for flexibility
- [ ] Validate custom sizes to avoid unintended rendering issues
- [ ] Add this option alongside the preset sizes in the UI for easy access

### Optional Sections:

- **Priority**: Medium
- **Are you willing to submit a PR for this enhancement?** Yes
- **Does this enhancement require changes in documentation?** No

**Comment by rahulchaudhary2244** [comment]
Hi @suryanshsingh2001, I would like to work on this enhancement.

**Comment by suryanshsingh2001** [comment]
Hey @rahulchaudhary2244 
Sure! Please make sure that the changes work with the existing screen sizes and ensure the design is responsive. Also, follow the same UI design patterns used for the previous controls. Looking forward to your contribution!
